### ISSUE TITLE
[bug] breaks IE11

### ISSUE THREAD

**Issue by djeglin** [bsonntag/parse-css-transition#1]
This module breaks whatever application it is loaded as a part of in IE11, as it uses array destructuring for variable assignment.

**Comment by djeglin** [comment]
I noticed that @onrunning has a fork which already addresses this issue. Suggest that the PR I just created is accepted and merged here as it appears to resolve the issue.

**Comment by bsonntag** [comment]
While that worked, having transpiled code as the source is not a good solution. Instead I'd prefer to setup babel to transpile the es6 source.

**Comment by bsonntag** [comment]
This should now be fixed. Can you please confirm?

**Comment by bsonntag** [comment]
Closing as this has been inactive for a long time. If the problem persists I can reopen again.
